cmake_minimum_required(VERSION 3.28)

project(opencv
    VERSION 1.0.0
    DESCRIPTION ""
    HOMEPAGE_URL ""
    LANGUAGES CXX
)

FILE(GLOB Src_OpenCV CONFIGURE_DEPENDS *.h *.cpp *.hpp)
source_group(Src_OpenCV FILES ${Src_OpenCV})

set(PROJECT_SOURCES
    ${Src_OpenCV}
)
add_executable(
    ${PROJECT_NAME}
    ${PROJECT_SOURCES}
)

include(Dependencies.cmake)
target_include_directories(${PROJECT_NAME} PRIVATE 
    $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}>
)
target_compile_definitions(${PROJECT_NAME} PRIVATE
    PROJECT_DIRECTORY="${CMAKE_CURRENT_SOURCE_DIR}"
    LINN_PROPERTY_ENABLE_SHORT_MACROS
    LINN_SINGLETON_ENABLE_SHORT_MACROS
)
set_target_properties(${PROJECT_NAME} PROPERTIES
    MACOSX_BUNDLE_BUNDLE_VERSION ${PROJECT_VERSION}
    MACOSX_BUNDLE_SHORT_VERSION_STRING ${PROJECT_VERSION_MAJOR}.${PROJECT_VERSION_MINOR}
    MACOSX_BUNDLE ON
    WIN32_EXECUTABLE OFF          # ON = 关闭控制台窗口（Windows GUI应用）
    LINK_WHAT_YOU_USE ON
    VS_DEBUGGER_WORKING_DIRECTORY "${CMAKE_RUNTIME_OUTPUT_DIRECTORY}"
    VS_DEBUGGER_COMMAND "$<TARGET_FILE:${PROJECT_NAME}>"
)